# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Snapchat Monopoly' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Snapchat Monopoly

  target 'Snapchat MonopolyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Snapchat MonopolyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
